### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by webtaculars**
#### Related issues

- None

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

Fix broken links in README.md

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
Thanks for the contribution! Can you sign the CLA? https://cla.strongloop.com/agreements/strongloop/loopback-example-database

Can you change the commit message to "Fix broken links in README.md" also?

**Comment by webtaculars** [comment]
Not able to change the commit message. I have signed the CLA.

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
@kjdelisle :gift:

**Comment by kjdelisle** [comment]
@crandmck PTAL

**Comment by crandmck** [comment]
@webtaculars Thanks! Changes LGTM.
@superkhau Must we change the commit msg, or can we just land it?

**Comment by superkhau** [comment]
@crandmck The CLA + the commit message (at least to `Update README.md` (instead of `README.me`. You can help change it when landing after @webtaculars responds.

@webtaculars Do you want to sign the CLA so we can help move this PR forward?

**Comment by loay** [comment]
@webtaculars 
if you don't sign the CLA, we can't do anything with this PR. Please sign it so we can land it. Thanks.

**Comment by loay** [comment]
@crandmck Links do not seem broken to me. They are working fine on my end!

**Comment by kjdelisle** [comment]
@webtaculars We're not saying that we don't want your contribution. We need certain legal guarantees provided by your acceptance of the CLA to accept code from you. If you agree to the CLA, then we can clean up the commit formatting and merge your changes.

**Comment by crandmck** [comment]
> Links do not seem broken to me. They are working fine on my end!

@loay The links would work in GitHub, but not when we use the README in the docs (for example) here:
https://loopback.io/doc/en/lb3/Connecting-to-PostgreSQL.html#create-the-collection-with-sample-data---automigration

This is why we ask folks to use absolute URLs in README links (cf https://loopback.io/doc/en/contrib/Markdown-style-guide.html#use-absolute-urls-in-readmes).

@kjdelisle the OP [said he signed the CLA](#issuecomment-267806931) but CI still says he has not.. so not sure what to do (?)  First, I'll try to run tests again and see if that clears it up...

**Comment by crandmck** [comment]
@slnode test please

**Comment by superkhau** [comment]
>@kjdelisle the OP said he signed the CLA but CI still says he has not.. so not sure what to do (?) First, I'll try to run tests again and see if that clears it up...

@rmg Can you help with this?

**Comment by superkhau** [comment]
Closing as abandoned. @crandmck Feel free to submit your own PR to fix the links.

@webtaculars Thanks for the contribution, please feel free to comment again and we'll reopen this in the future if it's still relevant.

**Pull request closed without merging**
